Use correct dev path.

diff --git a/btrfs-activate b/btrfs-activate
--- a/btrfs-activate
+++ b/btrfs-activate
@@ -20,7 +20,7 @@ read -s -p "LUKS key: " luks_key
 for d in $DRIVES
 do
     dev=$(basename $(readlink /dev/disk/by-uuid/$d))
-    echo "$luks_key" | cryptsetup luksOpen "$dev" "crypt_$dev" || die "$dev decryption failed"
+    echo "$luks_key" | cryptsetup luksOpen "/dev/$dev" "crypt_$dev" || die "$dev decryption failed"
     echo "$dev decrypted"
 done
 
