Add more feedback text.

diff --git a/btrfs-activate b/btrfs-activate
--- a/btrfs-activate
+++ b/btrfs-activate
@@ -3,8 +3,6 @@
 # Based on:
 # http://marc.merlins.org/perso/btrfs/post_2014-04-27_Btrfs-Multi-Device-Dmcrypt.html
 
-### NOT TESTED
-
 die () {
     echo "$1"
     exit 1
@@ -27,4 +25,5 @@ done
 
 btrfs device scan
 mkdir -p /tank
-mount -o defaults,noatime /dev/disk/by-label/tank /tank
+mount -o defaults,noatime /dev/disk/by-label/tank /tank || die "Couldn't find btrfs tank"
+echo "btrfs /tank mounted"
